#! /usr/bin/env python2

# auto-generated, do not edit by hand

cfgforwarddict = {
  'CMDNOTOK': 2,
  'CMDGETTOPOLOGYMGRMBOXPTR': 19,
  'CMDSTART': 7,
  'CMDLOCALCONFIG': 18,
  'CMDSTOP': 8,
  'CMDOK': 1,
  'CMDOBGATEWAY': 20,
  'CMDUSERSCHEMAMGR': 11,
  'CMDBADLOGINMESSAGES': 6,
  'CMDGLOBALCONFIG': 17,
  'CMDANONYMOUSPING': 5,
  'CMDDEADLOCKMGR': 12,
  'CMDENGINE': 14,
  'CMDTRANSACTIONAGENT': 13,
  'CMDNONE': 0,
  'CMDGET': 3,
  'CMDLISTENER': 9,
  'CMDIBGATEWAY': 16,
  'CMDSET': 4,
  'CMDPGHANDLER': 21
}

cfgreversedict = {
  2: 'CMDNOTOK',
  19: 'CMDGETTOPOLOGYMGRMBOXPTR',
  7: 'CMDSTART',
  18: 'CMDLOCALCONFIG',
  8: 'CMDSTOP',
  1: 'CMDOK',
  20: 'CMDOBGATEWAY',
  11: 'CMDUSERSCHEMAMGR',
  6: 'CMDBADLOGINMESSAGES',
  17: 'CMDGLOBALCONFIG',
  5: 'CMDANONYMOUSPING',
  12: 'CMDDEADLOCKMGR',
  14: 'CMDENGINE',
  13: 'CMDTRANSACTIONAGENT',
  0: 'CMDNONE',
  3: 'CMDGET',
  9: 'CMDLISTENER',
  16: 'CMDIBGATEWAY',
  4: 'CMDSET',
  21: 'CMDPGHANDLER'
}

actortypesforwarddict = {
  'ACTOR_TOPOLOGYMGR': 1,
  'ACTOR_IBGATEWAY': 8,
  'ACTOR_PGHANDLER': 10,
  'ACTOR_TRANSACTIONAGENT': 3,
  'ACTOR_DEADLOCKMGR': 6,
  'ACTOR_LISTENER': 9,
  'ACTOR_NONE': 0,
  'ACTOR_USERSCHEMAMGR': 5,
  'ACTOR_ENGINE': 4,
  'ACTOR_OBGATEWAY': 7
}

actortypesreversedict = {
  1: 'ACTOR_TOPOLOGYMGR',
  8: 'ACTOR_IBGATEWAY',
  10: 'ACTOR_PGHANDLER',
  3: 'ACTOR_TRANSACTIONAGENT',
  6: 'ACTOR_DEADLOCKMGR',
  9: 'ACTOR_LISTENER',
  0: 'ACTOR_NONE',
  5: 'ACTOR_USERSCHEMAMGR',
  4: 'ACTOR_ENGINE',
  7: 'ACTOR_OBGATEWAY'
}

firstactorid = 100

