import os
from glob import glob

env = Environment()
env['ENV']['TERM'] = os.environ['TERM']
env.Replace(CXX="clang++")
env.Append(CCFLAGS="-g --std=c++11 -mcx16 -finline-functions "
                   "-Wall -Wno-deprecated -Wno-write-strings " 
                   "-I./ -I../src -I../deps/include")
env.Append(LIBPATH="../lib")
env.Append(LIBS = ["infinisql", "tbb", "lmdb"])

test_sources = [] #glob("src/*.cc")

sources = ['gtest/gtest-all.cc', 'gtest/gtest_main.cc'] + test_sources

env.Program('test', sources)
