import os
from glob import glob

Import(['env', 'libraries'])
test_env = env.Clone()
test_env.Append(CPPPATH=["#tests/gtest", "#src"])
test_env.Append(LIBPATH=["#src", "#src/decimal"])
test_env.Append(LIBS = libraries + ["tbb", "lmdb", "pthread"])

test_sources = ['src/test_field_value.cc', 'src/test_field.cc', 
               'src/test_table.cc', 'src/test_decimal.cc'] #glob("src/*.cc")

sources = ['gtest/gtest-all.cc', 'gtest/gtest_main.cc'] + test_sources

test_env.Program('test', sources)
