import os
from glob import glob

Import('env')
test_env = env.Clone()
test_env.Append(CPPATH=["gtest"])
test_env.Append(LIBPATH=["#src"])
test_env.Append(CXXFLAGS="-g -finline-functions ")
test_env.Append(LIBS = ["infinisql", "tbb", "lmdb", "pthread"])

test_sources = [] #glob("src/*.cc")

sources = ['gtest/gtest-all.cc', 'gtest/gtest_main.cc'] + test_sources

test_env.Program('test', sources)
