Import('env')

isql_env = env.Clone()
isql_env.Append(LIBS=['tbb', 'lmdb', 'pthread', 'zmq'])

lib_source = ['Field.cc', 'Lightning.cc', 'Catalog.cc', 
              'Metadata.cc', 'Schema.cc', 'Table.cc', 'Index.cc', 'User.cc',
              'globals.cc', 'PartitionGroup.cc', 'UserSchemaDb.cc']
          
lib = isql_env.Library('infinisql', lib_source)
Return('lib')
