
Import('env')
lib_env = env.Clone()

sources = ['Actor.cc', 'Topology.cc', 'TopologyManager.cc',
           'AdminListener.cc', 'TransactionAgent.cc', 'PartitionWriter.cc',
           'TransactionLogger.cc', 'UserSchemaManager.cc', 'ObGateway.cc',
           'IbGateway.cc', 'Listener.cc']

lib = lib_env.Library('actors', sources)
Return('lib')
