Import(['env', 'libraries'])

isql_env = env.Clone()
isql_env.Append(LIBS=libraries + ['tbb', 'lmdb', 'pthread', 'zmq'])
          
server_source = ['main.cc']

isql_env.Program('infinisqld', server_source)
