Import('env')

isql_env = env.Clone()
isql_env.Append(LIBS=['tbb', 'lmdb', 'pthread'])
isql_env.Append(CXXFLAGS='-g -O3 -finline-functions ')

lib_source = ['Field.cc', 'Serdes.cc', 'Lightning.cc', 'Catalog.cc', 
              'Metadata.cc', 'Schema.cc', 'Table.cc', 'Index.cc', 'User.cc']
          
server_source = ['main.cc']

lib = isql_env.Library('infinisql', lib_source)
isql_env.Append(LIBS=[lib])
isql_env.Program('infinisqld', server_source)
